name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['1.10', '1', 'pre']
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - name: Instantiate
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Run tests
        shell: julia --color=yes --project=. {0}
        run: |
          include("run_tests.jl")
